#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = 'python3 ClientRoom.py "%(auth_proxy)s %(token)s %(mapa)s  "1" '


# Get required arguments
try:
    proxy ,  token , mapa  = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <user> <password> <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'user': user,
    'auth_proxy': proxy
}



# Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
