#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys

# Define command to request new token
_COMMAND_ = 'python3 ClientRoom.py "%(server_proxy)s %(token)s %(mapa)s "1"'


# Get required arguments
try:
    server_proxy, token, mapa = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <server_proxy> <token> <mapa> '.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'server_proxy': server_proxy,
    'token':token,
    'mapa':mapa
}



# Show command output and exit
#print(proc.before.decode().strip())
sys.exit(0)
